library:
  source-dirs: src
tests:
  euler-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- containers
- base >= 4.7 && < 5
- monad-loops
- data-ordlist
- inline-c
- split
- process
- text

name: euler
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/euler
license: BSD3
executables:
  euler-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - euler
description: Please see the README on GitHub at <https://github.com/githubuser/euler#readme>
